y=list(range(1,9)) 
print(f"Fila A:   {y[0]}   {y[1]}   {y[2]}   {y[3]}   {y[4]}   {y[5]}   {y[6]}   {y[7]}") 
print(f"Fila B:   {y[0]}   {y[1]}   {y[2]}   {y[3]}   {y[4]}   {y[5]}   {y[6]}   {y[7]}") 
print(f"Fila C:   {y[0]}   {y[1]}   {y[2]}   {y[3]}   {y[4]}   {y[5]}   {y[6]}   {y[7]}") 
print(f"Fila D:   {y[0]}   {y[1]}   {y[2]}   {y[3]}   {y[4]}   {y[5]}   {y[6]}   {y[7]}") 